name: detekt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
   detekt:
     runs-on: ubuntu-latest

     steps:
       - name: "checkout"
         uses: actions/checkout@v2

       - name: "detekt"
         uses: natiginfo/action-detekt-all@1.16.0-RC1
         with:
          args: --fail-fast --config .github/workflows/detekt-config
          
